[tool.poetry]
name = "learning-app"
version = "0.1.0"
description = ""
authors = ["annett21 <annettarasevich@gmail.com>"]
readme = "README.md"
packages = [{include = "learning_app"}]

[tool.poetry.dependencies]
python = "^3.11"
Django = "^4.1.7"
djangorestframework = "^3.14.0"
python-dotenv = "^0.21.1"
psycopg2 = "^2.9.5"
six = "^1.16.0"
celery = {extras = ["redis"], version = "^5.2.7"}
factory-boy = "^3.2.1"
<<<<<<< HEAD
drf-yasg = "^1.21.5"
=======
time-machine = "^2.9.0"
>>>>>>> develop

[tool.poetry.group.dev.dependencies]
ptpython = "^3.0.22"
black = "^23.1.0"
flake8 = "^6.0.0"
django-extensions = "^3.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
