# Generated by Django 4.1.7 on 2023-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=24, unique=True)),
                ("password", models.CharField(max_length=16, null=True)),
                ("first_name", models.CharField(blank=True, max_length=16)),
                ("last_name", models.CharField(blank=True, max_length=16)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("document_number", models.CharField(max_length=16, unique=True)),
                ("is_student", models.BooleanField(default=False)),
                ("is_professor", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
