# Generated by Django 4.1.7 on 2023-02-22 12:42

import custom_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=24,
                validators=[custom_auth.models.username_validator],
            ),
        ),
    ]
