# Generated by Django 4.1.7 on 2023-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_professor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_student",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("AD", "Admin"),
                    ("PR", "Professor"),
                    ("ST", "Student"),
                    ("OOR", "Out of role"),
                ],
                default="OOR",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
