# Generated by Django 4.1.7 on 2023-02-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "custom_auth",
            "0002_remove_user_is_professor_remove_user_is_student_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("AD", "Admin"),
                    ("PR", "Professor"),
                    ("ST", "Student"),
                    ("GU", "Guest"),
                    ("OOR", "Out of role"),
                ],
                default="OOR",
                max_length=4,
            ),
        ),
    ]
