# Generated by Django 4.2 on 2023-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0004_user_email_confirmed_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="document_number",
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
